name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # ruby: [ '2.5', '2.6', '2.7' ]
        ruby: [ '2.6' ]
    steps:
      - uses: actions/checkout@v2
      - uses: Dovyski/setup-opencv-action@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # o
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python PyWavelets
      - name: Run tests
        run: bundle exec rspec

